# Generated by Django 5.1.15 on 2026-05-11 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Kasallik nomi')),
                ('icd_code', models.CharField(blank=True, max_length=10, verbose_name='ICD-10 Kod')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('symptoms', models.JSONField(default=dict, verbose_name='Simptomlar')),
                ('severity', models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high'), ('CRITICAL', 'critical')], default='MEDIUM', max_length=20, verbose_name="Og'irlik darajasi")),
                ('recommended_tests', models.JSONField(default=list, verbose_name='Tavsiya etiladigan tahlillar')),
                ('treatment_options', models.TextField(blank=True, verbose_name="Davolash yo'llari")),
                ('prevention', models.TextField(blank=True, verbose_name='Oldini olish')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kasallik Naqshi',
                'verbose_name_plural': 'Kasallik Naqshlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Session ID')),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Yakunlandi'), ('FAILED', 'Xatolik')], default='PENDING', max_length=20, verbose_name='Holat')),
                ('symptoms', models.JSONField(default=list, verbose_name='Simptomlar')),
                ('test_results', models.JSONField(blank=True, default=dict, verbose_name='Tahlil natijalari')),
                ('agent_states', models.JSONField(default=dict, verbose_name='Agent holatlari')),
                ('error_message', models.TextField(blank=True, verbose_name='Xatolik xabari')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yakunlangan vaqt')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Diagnostika Sessiyasi',
                'verbose_name_plural': 'Diagnostika Sessiyalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Ishonch darajasi')),
                ('recommended_tests', models.JSONField(default=list, verbose_name='Tavsiya etilgan tahlillar')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='Davolash rejasi')),
                ('agent_recommendations', models.JSONField(default=dict, verbose_name='Agent tavsiyalari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='diagnostics.diagnosticsession')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_results', to='diagnostics.diseasepattern')),
            ],
            options={
                'verbose_name': 'Diagnostika Natijasi',
                'verbose_name_plural': 'Diagnostika Natijalari',
                'ordering': ['-confidence_score'],
            },
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['session_id'], name='diagnostics_session_d7b0df_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticsession',
            index=models.Index(fields=['status', 'started_at'], name='diagnostics_status_449d2c_idx'),
        ),
    ]
