# Generated by Django 5.1.15 on 2026-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ACLMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('performative', models.CharField(choices=[('INFORM', "Inform - Ma'lumot berish"), ('REQUEST', "Request - So'rov yuborish"), ('QUERY', 'Query - Savol berish'), ('PROPOSE', 'Propose - Taklif qilish'), ('ACCEPT', 'Accept - Qabul qilish'), ('REJECT', 'Reject - Rad etish'), ('CONFIRM', 'Confirm - Tasdiqlash'), ('FAILURE', 'Failure - Xatolik haqida xabar')], default='INFORM', max_length=20)),
                ('sender', models.CharField(db_index=True, max_length=100)),
                ('receiver', models.CharField(db_index=True, max_length=100)),
                ('content', models.JSONField(default=dict)),
                ('in_reply_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ACL Xabar',
                'verbose_name_plural': 'ACL Xabarlar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='core_aclmes_sender_ddeb60_idx'), models.Index(fields=['performative', 'is_processed'], name='core_aclmes_perform_425360_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, max_length=100)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Agent Log',
                'verbose_name_plural': 'Agent Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent_name', 'level'], name='core_agentl_agent_n_be5acc_idx'), models.Index(fields=['timestamp'], name='core_agentl_timesta_515af9_idx')],
            },
        ),
    ]
