# Generated by Django 5.1.15 on 2026-05-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100, unique=True, verbose_name='Agent nomi')),
                ('state', models.CharField(choices=[('IDLE', "Bo'sh"), ('PROCESSING', 'Ishlamoqda'), ('WAITING', 'Kutmoqda'), ('COMPLETED', 'Yakunlandi'), ('FAILED', 'Xatolik')], default='IDLE', max_length=20, verbose_name='Holat')),
                ('current_task', models.CharField(blank=True, max_length=200, verbose_name='Hozirgi vazifa')),
                ('metadata', models.JSONField(default=dict, verbose_name='Metadata')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faoliyat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent Holati',
                'verbose_name_plural': 'Agent Holatlari',
                'ordering': ['agent_name'],
            },
        ),
    ]
