# Generated by Django 5.1.15 on 2026-05-11 18:49

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol'), ('O', 'Boshqa')], max_length=1, verbose_name='Jins')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Qon guruhi')),
                ('height', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)], verbose_name="Bo'yi (sm)")),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(500)], verbose_name='Vazni (kg)')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergiyalar')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Surunkali kasalliklar')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200, verbose_name='Kasallik')),
                ('diagnosed_at', models.DateField(verbose_name='Tashxis sanasi')),
                ('treatment', models.TextField(blank=True, verbose_name='Davolash')),
                ('outcome', models.TextField(blank=True, verbose_name='Natija')),
                ('doctor_name', models.CharField(blank=True, max_length=200, verbose_name='Shifokor')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Tibbiy Tarix',
                'verbose_name_plural': 'Tibbiy Tarix',
                'ordering': ['-diagnosed_at'],
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Simptom')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('severity', models.CharField(choices=[('LOW', 'Engil'), ('MEDIUM', "O'rtacha"), ('HIGH', "Og'ir"), ('CRITICAL', 'Kritik')], default='MEDIUM', max_length=20, verbose_name="Og'irlik darajasi")),
                ('started_at', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Davomiyligi (kun)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Simptom',
                'verbose_name_plural': 'Simptomlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_of_birth'], name='patients_pa_date_of_4302f5_idx'),
        ),
    ]
