# Generated by Django 4.2.30 on 2026-05-12 03:58

from django.db import migrations, models
import json


def convert_text_to_json(apps, schema_editor):
    """Convert TextField data to JSON format."""
    Patient = apps.get_model('patients', 'Patient')
    
    for patient in Patient.objects.all():
        # Convert allergies
        if patient.allergies and isinstance(patient.allergies, str):
            # Split by comma or newline
            allergies_list = [a.strip() for a in patient.allergies.replace('\n', ',').split(',') if a.strip()]
            patient.allergies = allergies_list
        elif not patient.allergies:
            patient.allergies = []
        
        # Convert chronic_diseases
        if patient.chronic_diseases and isinstance(patient.chronic_diseases, str):
            diseases_list = [d.strip() for d in patient.chronic_diseases.replace('\n', ',').split(',') if d.strip()]
            patient.chronic_diseases = diseases_list
        elif not patient.chronic_diseases:
            patient.chronic_diseases = []
        
        patient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Favqulodda aloqa'),
        ),
        # First, make fields nullable temporarily
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, null=True, verbose_name='Allergiyalar'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='Surunkali kasalliklar'),
        ),
        # Convert data
        migrations.RunPython(convert_text_to_json, migrations.RunPython.noop),
        # Now change to JSONField
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.JSONField(blank=True, default=list, verbose_name='Allergiyalar'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='chronic_diseases',
            field=models.JSONField(blank=True, default=list, verbose_name='Surunkali kasalliklar'),
        ),
    ]
